<template>
<div>
    <div class="header">
        <el-row style="width: 100%;">
          <el-col :span="8"><div>MEMO</div></el-col>
          <el-col :span="8"><div /></el-col>
          <el-col :span="8"><div>退出</div></el-col>
        </el-row>
    </div>
    <div class="wrap">
        <div class="left">
            <p>111111111111111111111111111111111</p>
        </div>
        <div class="right">
            <p>111111111</p>
            <p>111111111</p>
            <p>111111111</p>
            <p>111111111</p>
            <p>111111111</p>
            <p>111111111</p>
            <p>111111111</p>
            <p>111111111</p>
            <p>111111111</p>
            <p>111111111</p>
            <p>111111111</p>
            <p>111111111</p>
            <p>111111111</p>
            <p>111111111</p>
            <p>111111111</p>
            <p>111111111</p>
            <p>111111111</p>
            <p>111111111</p>
            <p>111111111</p>
            <p>111111111</p>
            <p>111111111</p>
            <p>111111111</p>
            <p>111111111</p>
            <p>111111111</p>
            <p>111111111</p>
            <p>111111111</p>
            <p>111111111</p>
            <p>111111111</p>
            <p>111111111</p>
            <p>111111111</p>
            <p>111111111</p>
            <p>111111111</p>
            <p>111111111</p>
            <p>111111111</p>
            <p>111111111</p>
            <p>111111111</p>
            <p>111111111</p>
            <p>111111111</p>
            <p>111111111</p>
            <p>111111111</p>
            <p>111111111</p>
            <p>111111111</p>
            <p>111111111</p>
            <p>111111111</p>
            <p>111111111</p>
            <p>111111111</p>
            <p>111111111</p>
            <p>111111111</p>
            <p>111111111</p>
            <p>111111111</p>
            <p>111111111</p>
            <p>111111111</p>
            <p>111111111</p>
            <p>111111111</p>
            <p>111111111</p>
            <p>111111111</p>
            <p>111111111</p>
            <p>111111111</p>
            <p>111111111</p>
            <p>111111111</p>
            <p>111111111</p>
        </div>
    </div>
</div>
</template>
<script>

</script>

<style scope>
html{
    background-color:  #f3f4f6;
}

.header {
    height: 50px;
    padding: 0 40px;
    position: relative;
    background: #fff;
    border-bottom: 1px solid #e5e5e5;
    box-shadow: 0 3px 2px -2px rgb(200 200 200 / 15%);
    display: flex;
}

.wrap{
    position: relative;
    padding: 10px 86px 0 86px;
}
.left{
    background-color: blue;
    float: left;
}
.right{
    background-color: red;
    float: right;
}
</style>